-- AlterTable
ALTER TABLE "Account" ALTER COLUMN "refresh_token" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "access_token" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "id_token" SET DATA TYPE VARCHAR(2048);
